#ifndef __have__Chords_h__
#define __have__Chords_h___

/** @addtogroup MIDI
 *  @{
 */

/**
 *  \file Chords.h
 *  \brief Music Chords support
 */

const int8_t chordNotesDef[][9] = {
    {1, 0},
    {1, 0},

    {2, 0, 7},
    {3, 0, 4, 8},
    {3, 0, 3, 6},
    {3, 0, 4, 7},
    {3, 0, 3, 7},
    {3, 0, 5, 7},
    {4, 0, 4, 8, 10},
    {4, 0, 4, 8, 11},
    {4, 0, 4, 7, 10},
    {4, 0, 5, 6, 7},
    {4, 0, 4, 7, 9},
    {4, 0, 4, 7, 11},
    {4, 0, 3, 7, 9},
    {4, 0, 3, 7, 10},
    {5, 0, 4, 7, 11, 14},
    {5, 0, 3, 7, 10, 14},
    {7, 0, 4, 7, 11, 14, 18, 21},
    {7, 0, 3, 7, 10, 14, 17, 21},
    {8, 0, 1, 5, 6, 10, 12, 15, 17},
    {3, 0, 6, 10},
    {3, 0, 5, 8},
    {3, 0, 1, 6},
    {4, 0, 5, 7, 10},
    {4, 0, 3, 6, 9},
    {4, 0, 3, 6, 11},
    {4, 0, 4, 6, 10},
    {4, 0, 3, 6, 10},
    {4, 0, 3, 7, 11},
    {4, 0, 2, 4, 7},
    {5, 0, 4, 7, 10, 15},
    {5, 0, 4, 7, 10, 13},
    {5, 0, 4, 7, 10, 14},
    {5, 0, 7, 9, 13, 16},
    {5, 0, 8, 11, 16, 21},
    {5, 0, 4, 7, 11, 18},
    {5, 0, 4, 7, 9, 14},
    {5, 0, 4, 8, 11, 18},
    {5, 0, 3, 7, 9, 14},
    {5, 0, 4, 8, 10, 14},
    {5, 0, 4, 6, 10, 14},
    {5, 0, 4, 7, 9, 10},
    {5, 0, 5, 10, 15, 19},
    {6, 0, 4, 7, 10, 14, 18},
    {6, 0, 4, 7, 10, 14, 17},
    {6, 0, 1, 4, 5, 8, 9},
    {6, 0, 4, 7, 11, 14, 17},
    {6, 0, 3, 7, 10, 14, 17},
    {6, 0, 6, 10, 16, 21, 14},
    {6, 0, 1, 4, 6, 7, 10},
    {7, 0, 4, 7, 10, 14, 17, 21},

    {0, 0, 0, 0, 0, 0, 0, 0, 0}
};

static const char *const ChordNames[] = {
    "Default",
    "No Chord",

    "Power P5",
    "Augmented",
    "Diminished",
    "Major",
    "Minor",
    "Suspended",
    "Aug 7th",
    "Aug major 7th",
    "Dom 7th",
    "Dream",
    "Major 6th",
    "Major 7th",
    "Minor 6th",
    "Minor 7th",
    "Major 9th",
    "Minor 9h",
    "Major 13th",
    "Minor 13th",
    "Magic",
    "Aug 6th italian",
    "Neapolitan",
    "Viennese trichord",
    "7th suspension four",
    "Dim 7th ",
    "Dim major 7th",
    "Dom 7th flat five",
    "HalfDim 7th",
    "Minor major 7th",
    "Mu",
    "Dom 7th sharp nine",
    "Dom minor 9th",
    "Dom 9th",
    "Elektra",
    "Farben",
    "Lydian",
    "Major 6th ninth",
    "Major 7th sharp 11th",
    "Minor 6th ninth",
    "Ninth Aug. 5th",
    "Ninth flat 5th",
    "Seven six",
    "So What",
    "Aug 11th",
    "Dom 11th",
    "Hexachord",
    "Major 11th",
    "Minor 11th",
    "Mystic",
    "Petrushka",
    "Dom 13th",

    "Last Chord"
};

static const char *const LongChordNames[] = {
    "Default",
    "No Chord",

    "Power chord P5",
    "Augmented chord",
    "Diminished chord",
    "Major chord",
    "Minor chord",
    "Suspended chord",
    "Augmented seventh chord",
    "Augmented major seventh chord",
    "Dominant seventh chord",
    "Dream chord",
    "Major sixth chord",
    "Major seventh chord",
    "Minor sixth chord",
    "Minor seventh chord",
    "Major ninth chord",
    "Minor ninth chord",
    "Major thirteenth chord",
    "Minor thirteenth chord",
    "Magic chord",
    "Augmented sixth chord italian",
    "Neapolitan chord",
    "Viennese trichord",
    "Seventh suspension four chord",
    "Diminished seventh chord ",
    "Diminished major seventh chord",
    "Dominant seventh flat five chord",
    "Half-diminished seventh chord",
    "Minor major seventh chord",
    "Mu chord",
    "Dominant seventh sharp nine / Hendrix chord",
    "Dominant minor ninth",
    "Dominant ninth",
    "Elektra chord",
    "Farben chord",
    "Lydian chord",
    "Major sixth ninth chord",
    "Major seventh sharp eleventh chord",
    "Minor sixth ninth chord (6/9)",
    "Ninth augmented fifth chord",
    "Ninth flat fifth chord",
    "Seven six chord",
    "So What chord",
    "Augmented eleventh chord",
    "Dominant eleventh chord",
    "Hexachord Ode-to-Napoleon",
    "Major eleventh chord",
    "Minor eleventh chord",
    "Mystic chord",
    "Petrushka chord",
    "Dominant thirteenth chord",

    "Last Chord,do not use"
};

enum
{
    DEF_CHORD = 0,
    ONENOTECHORD,

    POWER_P5,
    AUGMENTED,
    DIMINISHED,
    MAJOR,
    MINOR,
    SUSPENDED,
    AUG_7TH,
    AUG_MAJOR_7TH,
    DOM_7TH,
    DREAM,
    MAJOR_6TH,
    MAJOR_7TH,
    MINOR_6TH,
    MINOR_7TH,
    MAJOR_NINTH,
    MINOR_NINTH,
    MAJOR_13TH,
    MINOR_13TH,
    MAGIC,
    AUG_6TH_ITALIAN,
    NEAPOLITAN,
    VIENNESE_TRICHORD,
    SEVTH_SUSPENSION_FOUR,
    DIM_7TH,
    DIM_MAJOR_7TH,
    DOM_7TH_FLAT_FIVE,
    HALFDIM_7TH,
    MINOR_MAJOR_7TH,
    MU,
    DOM_7TH_SHARP_NINE,
    DOM_MINOR_NINTH,
    DOM_NINTH,
    ELEKTRA,
    FARBEN,
    LYDIAN,
    MAJOR_6TH_NINTH,
    MAJOR_7TH_SHARP_11TH,
    MINOR_6TH_NINTH,
    NINTH_AUG_FIFTH,
    NINTH_FLAT_FIFTH,
    SEVEN_SIX,
    SO_WHAT,
    AUG_11TH,
    DOM_11TH,
    HEXACHORD,
    MAJOR_11TH,
    MINOR_11TH,
    MYSTIC,
    PETRUSHKA,
    DOM_13TH,

    LASTCHORD
};

/** @} */

#endif
