var annotated_dup =
[
    [ "AnalogPort", "class_analog_port.html", "class_analog_port" ],
    [ "AnInputPortCfg", "class_an_input_port_cfg.html", "class_an_input_port_cfg" ],
    [ "Blinker", "class_blinker.html", "class_blinker" ],
    [ "DemuxAnalogPort", "class_demux_analog_port.html", "class_demux_analog_port" ],
    [ "DigitalPort", "class_digital_port.html", "class_digital_port" ],
    [ "DigPortCfg", "class_dig_port_cfg.html", "class_dig_port_cfg" ],
    [ "GenericSysExPacket", "struct_generic_sys_ex_packet.html", "struct_generic_sys_ex_packet" ],
    [ "GlobalCfg", "class_global_cfg.html", "class_global_cfg" ],
    [ "InputControl", "class_input_control.html", "class_input_control" ],
    [ "InputCtrlCfg", "class_input_ctrl_cfg.html", "class_input_ctrl_cfg" ],
    [ "InputPort", "class_input_port.html", "class_input_port" ],
    [ "InputPortCfg", "class_input_port_cfg.html", "class_input_port_cfg" ],
    [ "MenuClass", "class_menu_class.html", "class_menu_class" ],
    [ "MenuItem_t", "struct_menu_item__t.html", "struct_menu_item__t" ],
    [ "MenuList", "class_menu_list.html", "class_menu_list" ],
    [ "MIDImerger", "class_m_i_d_imerger.html", "class_m_i_d_imerger" ],
    [ "OLEDMenu", "class_o_l_e_d_menu.html", "class_o_l_e_d_menu" ],
    [ "OSCmerger", "class_o_s_cmerger.html", "class_o_s_cmerger" ],
    [ "RangeConv", "class_range_conv.html", "class_range_conv" ],
    [ "SaveLoadClass", "class_save_load_class.html", "class_save_load_class" ],
    [ "SLIPEncodedUSBSerial", "class_s_l_i_p_encoded_u_s_b_serial.html", "class_s_l_i_p_encoded_u_s_b_serial" ],
    [ "VCMCApp", "class_v_c_m_c_app.html", "class_v_c_m_c_app" ],
    [ "VCMCSysExPacket", "struct_v_c_m_c_sys_ex_packet.html", "struct_v_c_m_c_sys_ex_packet" ],
    [ "VCMCSysExPar", "struct_v_c_m_c_sys_ex_par.html", "struct_v_c_m_c_sys_ex_par" ]
];