// MIDI Functions for analog ports
//public enum InputFunctions { PITCHTRIG, PITCH, VELOCITY, CONTROLCHANGE, PROGRAMCHANGE, PITCHBEND, PERCENT, ANAGCLOCK, ANAGSTARTSTOP, ANAGPAUSECONT, ANAGTRIGSTARTSTOP, ANAGTRIGPAUSECONT, ANAGFREEVALUE }
// MIDI Functions for digital ports
//public enum GateFunctions { TRIGGER, LATCH, CCBUT, GATECLOCK, GATESTARTSTOP, GATEPAUSECONT, GATETRIGSTARTSTOP, GATETRIGPAUSECONT, GATESTART, GATESTOP, GATECONTINUE }
